project: instagram
region: ap-southeast-2
env: dev
state_bucket: instagram-terraform-state-dev
modules: ../../infrastructure/modules
state_file:
ecr_account_id:
ecr_account_region:
slack_deployment_webhook:

# setup backend, always deployed
health_endpoint:
image_bucket_postfix:
# you can set docker command from here
# backend_container_command: ["config", "some_value"]
# backend_image_port: 8765
# setup push notification FCM SNS for backend
setup_FCM_SNS: false
backend_env_variables:
  env1: value1

# setup services
services:
  - name: service1
    remote_access: true
    container_port: 3000
    host_port: 3000
    cpu: 256
    memory: 512
    xray_enabled: false
    env_vars:
      SERVICE_TEST: PASSED

# Route53 domain management
setup_domain: true
domain: instagram.madappgang.com.au

# setup postgres
setup_postgres: true
pg_db_name: instagram
pg_username: dbadmin
pgadmin: false
pgadmin_email: admin@admin.com
## optional postgres
pg_public: true
pg_engine: "14"

# setup cognito
setup_cognito: true
# it can be an empty list if we want to skip the verification process
auto_verified_attributes:
  - email
enable_web_client: false
enable_dashboard_client: false
dashboard_callback_urls:
  - https://jwt.io
enable_user_pool_domain: false
user_pool_domain_prefix:
allow_backend_task_to_confirm_signup: false

# setup scheduled tasks
scheduled_tasks:
  - name: task1
    schedule: rate(1 minutes)
  - name: task2
    schedule: rate(1 hours)

# setup event processing tasks
event_processor_tasks:
  - name: event_task1
    rule_name: hug_all
    sources:
      - service1
      - service2
    detail_types:
      - SERVICE_DEPLOYMENT_COMPLETED
      - SERVICE_DEPLOYMENT_FAILED
      - SERVICE_DEPLOYMENT_IN_PROGRESS

# setup AWS SES
setup_ses: true
#optional, if ses uses different domain
ses_domain:
ses_test_emails:
  - i@madappgang.com
  - ivan.holiak@madappgang.com
efs:
  - name: uploads
  - name: static
