project: instagram
region: ap-southeast-2
env: dev
state_bucket: instagram-terraform-state-dev
modules: ../../infrastructure/modules
state_file:
ecr_account_id:
ecr_account_region:
slack_deployment_webhook:

# setup backend, always deployed
health_endpoint:
image_bucket_postfix:
# you can set docker command from here
# backend_container_command: ["config", "some_value"]
# backend_image_port: 8765
# setup push notification FCM SNS for backend
setup_FCM_SNS: false
backend_env_variables:
  env1: value1

# setup services
services:
  - name: service1
    remote_access: true
    container_port: 3000
    host_port: 3000
    cpu: 256
    memory: 512
    xray_enabled: false
    env_vars:
      SERVICE_TEST: PASSED

# Route53 domain management
setup_domain: true
domain: instagram.madappgang.com.au

# setup postgres
setup_postgres: true
pg_db_name: instagram
pg_username: dbadmin
pgadmin: false
pgadmin_email: admin@admin.com
## optional postgres
pg_public: true
pg_engine: "14"

# setup cognito
setup_cognito: true
# it can be an empty list if we want to skip the verification process
auto_verified_attributes:
  - email
enable_web_client: false
enable_dashboard_client: false
dashboard_callback_urls:
  - https://jwt.io
enable_user_pool_domain: false
user_pool_domain_prefix:
allow_backend_task_to_confirm_signup: false

# setup scheduled tasks
scheduled_tasks:
  - name: task1
    schedule: rate(1 minutes)
  - name: task2
    schedule: rate(1 hours)

# setup event processing tasks
event_processor_tasks:
  - name: event_task1
    rule_name: hug_all
    sources:
      - service1
      - service2
    detail_types:
      - SERVICE_DEPLOYMENT_COMPLETED
      - SERVICE_DEPLOYMENT_FAILED
      - SERVICE_DEPLOYMENT_IN_PROGRESS

# setup AWS SES
setup_ses: true
#optional, if ses uses different domain
ses_domain:
ses_test_emails:
  - i@madappgang.com
  - ivan.holiak@madappgang.com
efs:
  - name: uploads
  - name: static

# setup AWS Amplify for frontend deployments
amplify_apps:
  - name: main-web
    github_repository: https://github.com/username/repo
    # Multiple branches support - new format
    branches:
      - name: main
        stage: PRODUCTION
        enable_auto_build: true
        enable_pull_request_preview: true
        environment_variables:
          REACT_APP_API_URL: https://api.instagram.madappgang.com.au
          REACT_APP_COGNITO_REGION: ap-southeast-2
          REACT_APP_COGNITO_USER_POOL_ID: ${cognito_user_pool_id}
          REACT_APP_COGNITO_CLIENT_ID: ${cognito_web_client_id}
          REACT_APP_ENV: production
      - name: develop
        stage: DEVELOPMENT
        enable_auto_build: true
        enable_pull_request_preview: true
        environment_variables:
          REACT_APP_API_URL: https://api-dev.instagram.madappgang.com.au
          REACT_APP_COGNITO_REGION: ap-southeast-2
          REACT_APP_COGNITO_USER_POOL_ID: ${cognito_user_pool_id}
          REACT_APP_COGNITO_CLIENT_ID: ${cognito_web_client_id}
          REACT_APP_ENV: development
      - name: staging
        stage: BETA
        enable_auto_build: true
        enable_pull_request_preview: false
        environment_variables:
          REACT_APP_API_URL: https://api-staging.instagram.madappgang.com.au
          REACT_APP_COGNITO_REGION: ap-southeast-2
          REACT_APP_COGNITO_USER_POOL_ID: ${cognito_user_pool_id}
          REACT_APP_COGNITO_CLIENT_ID: ${cognito_web_client_id}
          REACT_APP_ENV: staging
    # Legacy single branch format (still supported)
    # branch_name: main
    custom_domain: instagram.madappgang.com.au
    sub_domains:
      - www
      - app
    enable_root_domain: true
    # This is now deprecated when using branches array
    # enable_pr_preview: true
    # App-level environment variables (deprecated - use branch-specific vars)
    # environment_variables:
    #   REACT_APP_API_URL: https://api.instagram.madappgang.com.au
  # Example of second app (admin dashboard) with single branch (legacy format)
  # - name: admin-dashboard
  #   github_repository: https://github.com/username/admin-repo
  #   branch_name: main
  #   custom_domain: admin.instagram.madappgang.com.au
  #   sub_domains: []
  #   enable_root_domain: true
  #   enable_pr_preview: false
  #   environment_variables:
  #     VUE_APP_API_URL: https://api.instagram.madappgang.com.au
