account_id: ""
alb:
  enabled: true
amplify_apps:
- branches:
  - enable_auto_build: true
    enable_pull_request_preview: true
    environment_variables:
      REACT_APP_API_URL: https://api.instagram.madappgang.com.au
      REACT_APP_COGNITO_CLIENT_ID: ${cognito_web_client_id}
      REACT_APP_COGNITO_REGION: ap-southeast-2
      REACT_APP_COGNITO_USER_POOL_ID: ${cognito_user_pool_id}
      REACT_APP_ENV: production
    name: main
    stage: PRODUCTION
  - enable_auto_build: true
    enable_pull_request_preview: true
    environment_variables:
      REACT_APP_API_URL: https://api-dev.instagram.madappgang.com.au
      REACT_APP_COGNITO_CLIENT_ID: ${cognito_web_client_id}
      REACT_APP_COGNITO_REGION: ap-southeast-2
      REACT_APP_COGNITO_USER_POOL_ID: ${cognito_user_pool_id}
      REACT_APP_ENV: development
    name: develop
    stage: DEVELOPMENT
  - enable_auto_build: true
    enable_pull_request_preview: false
    environment_variables:
      REACT_APP_API_URL: https://api-staging.instagram.madappgang.com.au
      REACT_APP_COGNITO_CLIENT_ID: ${cognito_web_client_id}
      REACT_APP_COGNITO_REGION: ap-southeast-2
      REACT_APP_COGNITO_USER_POOL_ID: ${cognito_user_pool_id}
      REACT_APP_ENV: staging
    name: staging
    stage: BETA
  custom_domain: instagram.madappgang.com.au
  enable_root_domain: true
  github_repository: https://github.com/username/repo
  name: main-web
  sub_domains:
  - www
  - app
aws_profile: ""
cognito:
  auto_verified_attributes:
  - email
  backend_confirm_signup: false
  dashboard_callback_urls:
  - https://jwt.io
  enable_dashboard_client: false
  enable_user_pool_domain: false
  enable_web_client: false
  enabled: true
  user_pool_domain_prefix: null
domain:
  create_domain_zone: false
  domain_name: instagram.madappgang.com.au
  enabled: true
ecr_account_id: null
ecr_account_region: null
ecr_strategy: local
efs:
- name: uploads
- name: static
env: dev
event_processor_tasks:
- detail_types:
  - SERVICE_DEPLOYMENT_COMPLETED
  - SERVICE_DEPLOYMENT_FAILED
  - SERVICE_DEPLOYMENT_IN_PROGRESS
  name: event_task1
  rule_name: hug_all
  sources:
  - service1
  - service2
modules: ../../infrastructure/modules
postgres:
  aurora: true
  dbname: instagram
  enabled: true
  engine_version: "14"
  max_capacity: 1
  min_capacity: 0
  public_access: true
  username: dbadmin
project: instagram
pubsub_appsync:
  auth_lambda: false
  enabled: false
  resolvers: false
  schema: false
region: ap-southeast-2
scheduled_tasks:
- name: task1
  schedule: rate(1 minutes)
- name: task2
  schedule: rate(1 hours)
schema_version: 7
services:
- container_port: 3000
  cpu: 256
  desired_count: 3
  env_vars:
    SERVICE_TEST: PASSED
  host_port: 3000
  memory: 512
  name: service1
  remote_access: true
  xray_enabled: false
ses:
  domain_name: null
  enabled: true
  test_emails:
  - i@madappgang.com
  - ivan.holiak@madappgang.com
slack_deployment_webhook: null
sqs:
  enabled: false
  name: default-queue
state_bucket: instagram-terraform-state-dev
state_file: null
use_default_vpc: true
vpc_cidr: 10.0.0.0/16
workload:
  backend_alb_domain_name: alb.instagram.madappgang.com.au
  backend_autoscaling_enabled: true
  backend_autoscaling_max_capacity: 10
  backend_autoscaling_min_capacity: 2
  backend_cpu: "512"
  backend_desired_count: 2
  backend_env_variables:
    env1: value1
  backend_health_endpoint: null
  backend_image_port: 8080
  backend_memory: "1024"
  bucket_postfix: null
  bucket_public: false
  enable_github_oidc: false
  github_actions:
    aws_region: ap-southeast-2
    branch: main
    ecr_repository: instagram-dev
    ecs_cluster: instagram-dev-cluster
    ecs_service: instagram-dev-backend
    iam_role_name: github-actions-role
    workflow_file: .github/workflows/deploy.yml
    workflow_name: Deploy to AWS
  github_oidc_subjects: []
  install_pg_admin: false
  pg_admin_email: admin@admin.com
  setup_fcnsns: false
  xray_enabled: false
